# Este es tu archivo .streamlit/config.toml

[server]
# Esta l√≠nea le da permiso al navegador para cargar scripts
contentSecurityPolicy = "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; object-src 'none';"